### ISSUE TITLE
Add Testing documentation to readme

### ISSUE THREAD

**Issue by boxxxie** [xapix-io/paos#11]
i tried `lein test` which gave me a response telling me that i don't have a project.clj
i'm not sure how to run the tests outside of a repl or using `clj`/`clojure` commands

**Comment by DeLaGuardo** [comment]
Thanks for the suggestion. I will add it into readme. Right now you can use `clj` tool by running the command `clj -A:test:runner` from the root of the project. It is described in CONTRIBUTING.md but it is worth to mention the same in the README. 

Please tell me if something is not working for you.
