### ISSUE TITLE
Could not resolve dependencies

### ISSUE THREAD

**Issue by orlando-mendoza** [xapix-io/paos#22]
I having this error when trying to launch my REPL or deploying to Heroku. 3 days ago I had no problems using paos.

```
Could not transfer artifact net.sf.saxon:saxon:pom:9 from/to jboss (https://repository.jboss.org/nexus/content/repositories/deprecated/): Connection reset
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

This is part of my project.clj

```
  :repositories [["enonic" "https://repo.enonic.com/public/"]]
  :dependencies 
               [[camel-snake-kebab "0.4.2"]
                 [clj-http "3.10.1"]
                 [environ "1.2.0"]
                 [integrant "0.8.0"]
                 [integrant/repl "0.3.1"]
                 [io.xapix/paos "0.2.4"]
                 [metosin/reitit "0.5.10"]
                 [org.clojure/clojure "1.10.1"]
                 [org.postgresql/postgresql "42.2.14"]
                 [ovotech/ring-jwt "1.3.0"]
                 [ring "1.8.2"]
                 [seancorfield/next.jdbc "1.1.613"]
                 [buddy "2.0.0"]
                 [clojure.java-time "0.3.2"]
                 [ring/ring-mock "0.4.0"]
                 [ring-cors "0.1.13"]]
``` 
No success searching for a solution and now I'm stuck. Will appreciate your help.

**Comment by enragedginger** [comment]
I think I ran into this awhile ago. This library is available on Maven Central now, so maybe try removing the enoic repo from your list (or add the necessary missing repo if enoic is required for something else of which I am not aware.

https://clojars.org/io.xapix/paos

**Comment by orlando-mendoza** [comment]
It's funny I tried that approach before but it didn't work. Now I did it again deleting my .m2 folder before removing the :repositories tag and my REPL launched and the deployment ran fluently. Thank you!

**Comment by zarkone** [comment]
@orlando-mendoza hope that issue is resolved! 

also, this might be relevant: https://clojure.org/reference/deps_and_cli#_classpath_caching

> `-Sforce` - ignore cache and force recomputation

**Comment by DeLaGuardo** [comment]
there is also 0.2.5 version available where net.sf.saxon:saxon:pom:9 is excluded from dependencies and replaced by net.sf.saxon:saxon:9.1.0.8
